config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  #recieve information from the database
  #---------------------------------------
  # The 'index' method has access to all of the items in the database
  get 'salads' => 'salad#index', as: 'salads'

  # The 'create' method submits the new user data to the database
  post 'salads' => 'salad#create'

  # The 'new' method adds information to the app
  get 'salads/new' => 'salad#new', as: 'new_salad'

  # The 'show' method looks for one item in the database by the id
  get 'salads/:id' => 'salad#show', as: 'salad'


  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/salad.rb
class Salad < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/salad_controller.rb
class SaladController < ApplicationController

    def index
      @salads = Salad.all 
    end

    def show
      @salad = Salad.find(params[:id])
    end

    def new 
      @salad = Salad.new
    end

    def create
      @salad = Salad.create(salad_params)
      if @salad.valid?
         redirect_to salads_path
      end
    end

    private
    def salad_params
      params.require(:salad).permit(:name, :description, :image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/salad_helper.rb
module SaladHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SaladCreationsBackend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/salad/index.html.erb
<h1>Salad Creations</h1>

<ul>
    <% @salads.each do |salad| %>
    <li><%= salad.name %></li>
    <p><%= link_to 'New Salad', new_salad_path %></p>
    <% end %>
</ul>

app/views/salad/new.html.erb
<h3>Add a New Salad Recipe</h3>
<%= form_with model: @salad do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name %>

    <br>

    <%= form.label :description %>
    <%= form.text_field :description %>

    <br>

    <%= form.label :image %>
    <%= form.text_field :image %>

    <br>

    <%= form.submit 'Add Salad' %>

<% end %>

app/views/salad/show.html.erb
<h3><%= @salad.name %></h3>
<p><%= @salad.description %></p>
<p><%= @salad.image %></p>